"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { format, formatDistanceToNow } from "date-fns";
import { ArrowRight, ArrowUpRight, BriefcaseBusiness, Building2, CalendarDays, RefreshCw, Sparkles, TrendingUp, WandSparkles } from "lucide-react";
import { request } from "@/lib/client";
import type { Application, Job, SourceRun } from "@/lib/types";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { CompanyAvatar } from "@/components/jobs/job-card";
import { SponsorBadge, SourceBadge } from "@/components/jobs/job-badges";
import { cn } from "@/lib/utils";
type Overview = { user: { name: string; email: string }; counts: { newJobs: number; friendly: number; open: number; companies: number; applications: number; resumes: number }; statusCounts: Record<string, number>; recentJobs: Job[]; friendlyJobs: Job[]; followUps: Application[]; lastRun: SourceRun | null; demo: boolean };
const stages = [{ name: "Saved", key: "SAVED", color: "bg-[#a69de3]" }, { name: "Applied", key: "APPLIED", color: "bg-[#7969e0]" }, { name: "Interviewing", key: "INTERVIEWING", color: "bg-[#62b7ad]" }, { name: "Offer", key: "OFFER", color: "bg-[#7ecb93]" }, { name: "Rejected", key: "REJECTED", color: "bg-[#e8a9a9]" }];
export default function DashboardPage() {
  const [data, setData] = useState<Overview | null>(null); const [refreshing, setRefreshing] = useState(false);
  useEffect(() => { request<Overview>("/api/overview").then(setData).catch(e => toast.error(e.message)); }, []);
  async function refresh() {
    setRefreshing(true);
    try { const { run } = await request<{ run: SourceRun }>("/api/jobs/refresh", { method: "POST", body: "{}" });
      if (run.errors.length) toast.warning(`Refresh finished with ${run.errors.length} unavailable source${run.errors.length > 1 ? "s" : ""}. Cached jobs were kept.`);
      else toast.success(`${run.added} new jobs found`);
      setData(await request<Overview>("/api/overview"));
    } catch (e) { toast.error(e instanceof Error ? e.message : "Refresh failed"); }
    finally { setRefreshing(false); }
  }
  const first = data?.user.name?.split(" ")[0] || "there";
  return <div className="space-y-7">
    <div className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-[11px] font-bold uppercase tracking-[.15em] text-primary">{format(new Date(), "EEEE, MMMM d, yyyy")}</p><h1 className="font-display text-[28px] font-extrabold tracking-[-.055em] sm:text-[32px]">Good to see you, {first}<span className="text-[#e3a86b]">.</span></h1><p className="mt-1.5 text-sm text-muted-foreground">Here&apos;s where things stand in your search.</p></div>
      <Button variant="outline" onClick={refresh} disabled={refreshing}><RefreshCw size={15} className={refreshing ? "animate-spin" : ""} />{refreshing ? "Checking sources…" : "Refresh jobs"}</Button></div>
    <div className="hero-gradient relative overflow-hidden rounded-[24px] border border-[#e1dcfa] px-6 py-7 dark:border-[#494075] sm:px-8 sm:py-8 xl:px-10">
      <div className="absolute -right-16 -top-24 h-64 w-64 rounded-full border border-white/70" /><div className="absolute right-10 top-0 h-52 w-52 rounded-full border border-white/65" /><div className="absolute -bottom-32 right-32 h-64 w-64 rounded-full bg-white/20 blur-3xl" />
      <div className="relative z-10 max-w-[58%] max-md:max-w-full"><span className="inline-flex items-center gap-1.5 rounded-full bg-white/70 px-3 py-1 text-[11px] font-bold text-[#5f50af] dark:bg-white/10 dark:text-[#d9d0ff]"><Sparkles size={12} /> YOUR NEXT CHAPTER</span><h2 className="mt-4 max-w-lg font-display text-[26px] font-extrabold leading-[1.2] tracking-[-.055em] text-[#272350] dark:text-white sm:text-[30px]">Find the work that moves you forward.</h2><p className="mt-2 max-w-md text-[13px] leading-6 text-[#6a658a] dark:text-[#c5bedf]">Verified roles, clear visa signals, and a place for every step of your search. You&apos;ve got this.</p>
        <div className="mt-5 flex flex-wrap gap-2.5"><Button asChild size="sm"><Link href="/jobs">Explore job feed <ArrowRight size={15} /></Link></Button><Button asChild size="sm" variant="outline" className="border-white/80 bg-white/60 text-[#453886] dark:border-[#695d9c] dark:bg-white/10 dark:text-white"><Link href="/resumes">Tailor a resume</Link></Button></div></div>
      <div aria-hidden="true" className="absolute bottom-[-20px] right-[4%] hidden h-[190px] w-[32%] min-w-[255px] rotate-[-5deg] rounded-t-[19px] border border-white/90 bg-white/85 p-4 shadow-[0_14px_45px_#51439326] backdrop-blur-md md:block dark:border-[#61578a] dark:bg-[#353057]/90"><div className="flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-widest text-[#9189af]">YOUR OPPORTUNITIES</span><span className="h-2 w-2 rounded-full bg-[#65c797]" /></div><div className="mt-5 flex items-center gap-2.5"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#e9e5ff] text-sm font-bold text-[#6354b1]">P</span><div><div className="h-2 w-[112px] rounded-full bg-[#d7d2e9]" /><div className="mt-2 h-1.5 w-[72px] rounded-full bg-[#ebe8f3]" /></div><span className="ml-auto rounded-md bg-[#e8f8ef] px-1.5 py-1 text-[9px] font-bold text-[#28845a]">VERIFIED</span></div><div className="mt-4 h-px bg-[#edeaf3]" /><div className="mt-4 flex items-center gap-2.5"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#e8f2fa] text-sm font-bold text-[#4d7da6]">A</span><div><div className="h-2 w-[95px] rounded-full bg-[#d7d2e9]" /><div className="mt-2 h-1.5 w-[65px] rounded-full bg-[#ebe8f3]" /></div><span className="ml-auto rounded-md bg-[#f1efff] px-1.5 py-1 text-[9px] font-bold text-[#7464c7]">SOURCE</span></div></div>
    </div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      {[
        { label: "New since last visit", value: data?.counts.newJobs, suffix: "fresh opportunities", icon: TrendingUp, color: "text-[#6758cf]", bg: "bg-[#f0edff] dark:bg-[#302a55]", href: "/jobs" },
        { label: "Sponsorship-friendly", value: data?.counts.friendly, suffix: "open positions", icon: Sparkles, color: "text-[#269670]", bg: "bg-[#eaf8f1] dark:bg-[#21453a]", href: "/jobs?friendly=true" },
        { label: "Your applications", value: data?.counts.applications, suffix: "in your pipeline", icon: BriefcaseBusiness, color: "text-[#d0804b]", bg: "bg-[#fff3e9] dark:bg-[#49372e]", href: "/applications" },
        { label: "Tracked companies", value: data?.counts.companies, suffix: "career boards", icon: Building2, color: "text-[#4e91c0]", bg: "bg-[#ecf5fb] dark:bg-[#253f51]", href: "/companies" },
      ].map(({ label, value, suffix, icon: Icon, color, bg, href }) => <Link href={href} key={label} className="card-hover surface block p-5"><div className="flex items-start justify-between"><span className={cn("flex h-10 w-10 items-center justify-center rounded-xl", bg, color)}><Icon size={19} /></span><ArrowUpRight size={16} className="text-muted-foreground/60" /></div><div className="mt-4 flex items-end gap-2">{value === undefined ? <Skeleton className="h-8 w-10" /> : <span className="font-display text-[29px] font-extrabold leading-none tracking-[-.06em]">{value}</span>}<span className="pb-0.5 text-[11px] text-muted-foreground">{suffix}</span></div><p className="mt-2 text-[12px] font-semibold text-muted-foreground">{label}</p></Link>)}
    </div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.65fr)_minmax(320px,1fr)]">
      <Card><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle>Fresh from the source</CardTitle><p className="mt-1 text-xs text-muted-foreground">Latest verified openings from companies you track</p></div><Link href="/jobs" className="inline-flex items-center gap-1 text-xs font-bold text-primary hover:underline">View all <ArrowRight size={14} /></Link></CardHeader>
        <CardContent className="space-y-0">{!data ? Array.from({ length: 4 }, (_, i) => <div key={i} className="flex gap-3 border-t border-border py-4"><Skeleton className="h-10 w-10" /><div className="flex-1 space-y-2"><Skeleton className="h-3 w-20" /><Skeleton className="h-4 w-1/2" /></div></div>) : data.recentJobs.length ? data.recentJobs.map(job => <div key={job.id} className="flex items-start gap-3 border-t border-border py-3.5 first:border-t-0"><CompanyAvatar name={job.companyName} size="sm" /><div className="min-w-0 flex-1"><Link href={`/jobs/${job.id}`} className="text-[13px] font-bold hover:text-primary">{job.title}</Link><p className="mt-0.5 truncate text-[11px] text-muted-foreground">{job.companyName} · {job.location || "Location not specified"}</p><div className="mt-2 flex flex-wrap items-center gap-2"><SourceBadge source={job.source} batch={job.ycBatch} /><SponsorBadge status={job.sponsorship} evidenceSource={job.evidenceSource} compact /><span className="text-[10px] text-muted-foreground">{job.postedAt ? `Posted ${formatDistanceToNow(new Date(job.postedAt), { addSuffix: true })}` : "Posted date unavailable"}</span></div><div className="mt-2 flex flex-wrap gap-3 text-[11px] font-semibold"><a href={job.originalUrl} target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">Apply on company site ↗</a>{job.hnUrl && <a href={job.hnUrl} target="_blank" rel="noopener noreferrer" className="text-muted-foreground hover:text-primary hover:underline">Original HN comment ↗</a>}</div></div></div>) : <p className="py-10 text-center text-sm text-muted-foreground">No roles yet. <Link href="/companies" className="text-primary underline">Track a company</Link> to get started.</p>}</CardContent></Card>
      <div className="space-y-5"><Card><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle>Your pipeline</CardTitle><p className="mt-1 text-xs text-muted-foreground">Every step counts</p></div><Link href="/applications" aria-label="View applications" className="text-primary"><ArrowUpRight size={19} /></Link></CardHeader><CardContent>
        <div className="mb-6 flex h-2.5 overflow-hidden rounded-full bg-muted">{stages.map(s => { const count = data?.statusCounts[s.key] || 0; return count ? <div key={s.key} className={cn(s.color, "h-full")} style={{ width: `${count / (data?.counts.applications || 1) * 100}%` }} title={`${s.name}: ${count}`} /> : null; })}</div>
        <div className="grid grid-cols-5 gap-1">{stages.map(s => <div key={s.key}><p className="font-display text-xl font-extrabold">{data?.statusCounts[s.key] ?? "–"}</p><p className="mt-1 truncate text-[10px] text-muted-foreground sm:text-[11px]"><span className={cn("mr-1 inline-block h-1.5 w-1.5 rounded-full", s.color)} />{s.name}</p></div>)}</div>
      </CardContent></Card>
      <Card><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle>Upcoming follow-ups</CardTitle><p className="mt-1 text-xs text-muted-foreground">Stay a step ahead</p></div><CalendarDays size={18} className="text-primary" /></CardHeader><CardContent>
        {!data ? <Skeleton className="h-14" /> : data.followUps.length ? <div className="space-y-3">{data.followUps.map(app => <Link href="/applications" key={app.id} className="flex items-center gap-3 rounded-xl bg-muted/55 p-3 hover:bg-muted"><span className="flex h-10 w-10 shrink-0 flex-col items-center justify-center rounded-lg bg-card text-primary"><span className="text-[9px] font-bold uppercase">{format(new Date(app.followUpAt!), "MMM")}</span><span className="text-sm font-extrabold leading-none">{format(new Date(app.followUpAt!), "d")}</span></span><div className="min-w-0"><p className="truncate text-xs font-bold">{app.companyName}</p><p className="truncate text-[11px] text-muted-foreground">{app.title}</p></div><ArrowUpRight size={14} className="ml-auto shrink-0 text-muted-foreground" /></Link>)}</div> : <div className="py-3 text-center"><p className="text-sm font-medium">All caught up 🎉</p><p className="mt-1 text-xs text-muted-foreground">Add a reminder to an application to see it here.</p></div>}
      </CardContent></Card></div>
    </div>
    <div className="grid gap-4 sm:grid-cols-2"><Link href="/resumes" className="group flex items-center gap-4 rounded-2xl border border-border bg-card p-5 shadow-soft hover:border-primary/40"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#f0edff] text-primary"><WandSparkles size={21} /></span><div className="flex-1"><p className="font-display text-sm font-bold">Make your resume sound like you</p><p className="mt-1 text-xs text-muted-foreground">Tailor it for a role, without stretching the truth.</p></div><ArrowUpRight size={17} className="text-muted-foreground group-hover:text-primary" /></Link><Link href="/companies" className="group flex items-center gap-4 rounded-2xl border border-border bg-card p-5 shadow-soft hover:border-primary/40"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#eaf7f0] text-[#29845e]"><Building2 size={21} /></span><div className="flex-1"><p className="font-display text-sm font-bold">Know who&apos;s hiring</p><p className="mt-1 text-xs text-muted-foreground">Add a company board or discover YC startups.</p></div><ArrowUpRight size={17} className="text-muted-foreground group-hover:text-primary" /></Link></div>
    <p className="text-center text-[11px] text-muted-foreground">{data?.lastRun ? `Last refresh ${formatDistanceToNow(new Date(data.lastRun.endedAt || data.lastRun.startedAt), { addSuffix: true })}` : data?.demo ? "Preview snapshot · checked September 23, 2026" : "Run your first refresh to check official sources"} <span className="mx-1.5">·</span> Always verify availability on the company site</p>
  </div>;
}
