"use client";
import { useEffect, useState } from "react";
import { useTheme } from "next-themes";
import { toast } from "sonner";
import { Check, CircleHelp, ExternalLink, KeyRound, LockKeyhole, Moon, Save, SlidersHorizontal, Sun, UserRound, } from "lucide-react";
import { request } from "@/lib/client";
import { Button } from "@/components/ui/button";
import { Input, Select } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { PageHeading } from "@/components/layout/page-heading";
import { Skeleton } from "@/components/ui/skeleton";
type Settings = { name: string; email: string; humanizationIntensity: "LIGHT" | "MEDIUM" | "STRONG"; humanizerUrl: string | null; detectorUrl: string | null; hasHumanizerKey: boolean; hasDetectorKey: boolean; hasLLM: boolean; demo: boolean };
export default function SettingsPage() {
  const [settings, setSettings] = useState<Settings | null>(null), [name, setName] = useState(""), [intensity, setIntensity] = useState<Settings["humanizationIntensity"]>("MEDIUM");
  const [humanizerUrl, setHumanizerUrl] = useState(""), [detectorUrl, setDetectorUrl] = useState(""), [humanizerKey, setHumanizerKey] = useState(""), [detectorKey, setDetectorKey] = useState(""), [busy, setBusy] = useState(false);
  const { theme, setTheme } = useTheme();
  useEffect(() => { request<{ settings: Settings }>("/api/settings").then(d => { setSettings(d.settings); setName(d.settings.name || ""); setIntensity(d.settings.humanizationIntensity); setHumanizerUrl(d.settings.humanizerUrl || ""); setDetectorUrl(d.settings.detectorUrl || ""); }).catch(e => toast.error(e.message)); }, []);
  async function save() { setBusy(true); try { const body: Record<string, unknown> = { name, humanizationIntensity: intensity, humanizerUrl, detectorUrl };
      if (humanizerKey) body.humanizerKey = humanizerKey;
      if (detectorKey) body.detectorKey = detectorKey;
      await request("/api/settings", { method: "PATCH", body: JSON.stringify(body) });
      setSettings(prev => prev && ({ ...prev, name, humanizationIntensity: intensity, humanizerUrl, detectorUrl,
        hasHumanizerKey: prev.hasHumanizerKey || !!humanizerKey, hasDetectorKey: prev.hasDetectorKey || !!detectorKey }));
      setHumanizerKey(""); setDetectorKey(""); toast.success("Preferences saved");
    } catch (e) { toast.error(e instanceof Error ? e.message : "Could not save settings"); } finally { setBusy(false); } }
  async function clearKey(which: "humanizerKey" | "detectorKey") {
    try { await request("/api/settings", { method: "PATCH", body: JSON.stringify({ [which]: "" }) }); setSettings(prev => prev && ({ ...prev, [which === "humanizerKey" ? "hasHumanizerKey" : "hasDetectorKey"]: false })); toast.success("Key removed"); }
    catch (e) { toast.error(e instanceof Error ? e.message : "Could not remove key"); }
  }
  return <div><PageHeading eyebrow="YOUR WORKSPACE" title="Settings" description="The little things that make this search feel like yours." action={<Button onClick={save} disabled={!settings || busy}><Save size={15} />{busy ? "Saving…" : "Save changes"}</Button>} />
    {!settings ? <div className="max-w-3xl space-y-4"><Skeleton className="h-44" /><Skeleton className="h-44" /><Skeleton className="h-44" /></div> : <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_290px]"><div className="space-y-5"><Card><CardHeader className="flex flex-row items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-accent text-primary"><UserRound size={19} /></span><div><CardTitle>Your profile</CardTitle><p className="mt-0.5 text-xs text-muted-foreground">The name you see around the workspace</p></div></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><div><label htmlFor="settings-name" className="mb-1.5 block text-xs font-bold">Display name</label><Input id="settings-name" value={name} onChange={e => setName(e.target.value)} /></div><div><label htmlFor="settings-email" className="mb-1.5 block text-xs font-bold">Email</label><Input id="settings-email" value={settings.email} readOnly disabled /></div></CardContent></Card>
      <Card><CardHeader className="flex flex-row items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#f0edff] text-primary dark:bg-[#382f5d]"><SlidersHorizontal size={19} /></span><div><CardTitle>Appearance & writing</CardTitle><p className="mt-0.5 text-xs text-muted-foreground">Set the tone for your space and your resume</p></div></CardHeader><CardContent className="space-y-5"><div><p className="mb-2 text-xs font-bold">Color theme</p><div className="flex gap-2"><button onClick={() => setTheme("light")} className={`flex w-28 items-center justify-center gap-2 rounded-xl border px-3 py-2.5 text-xs font-bold ${theme !== "dark" ? "border-primary bg-accent text-primary" : "border-border text-muted-foreground"}`}><Sun size={15} /> Light</button><button onClick={() => setTheme("dark")} className={`flex w-28 items-center justify-center gap-2 rounded-xl border px-3 py-2.5 text-xs font-bold ${theme === "dark" ? "border-primary bg-accent text-primary" : "border-border text-muted-foreground"}`}><Moon size={15} /> Dark</button></div></div><div className="border-t border-border pt-4"><label htmlFor="intensity" className="mb-1.5 block text-xs font-bold">Humanization intensity</label><Select id="intensity" value={intensity} onChange={e => setIntensity(e.target.value as Settings["humanizationIntensity"])} className="max-w-xs"><option value="LIGHT">Light — subtle cleanup</option><option value="MEDIUM">Medium — natural polish</option><option value="STRONG">Strong — concise and conversational</option></Select><p className="mt-2 text-[11px] text-muted-foreground">The built-in humanizer always runs, even without external providers. Every result still passes fact-lock.</p></div></CardContent></Card>
      <Card><CardHeader className="flex flex-row items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#eaf8f1] text-[#29885e] dark:bg-[#214033]"><KeyRound size={19} /></span><div><CardTitle>AI providers</CardTitle><p className="mt-0.5 text-xs text-muted-foreground">Your keys are encrypted at rest and never sent to the browser</p></div></CardHeader><CardContent className="space-y-5"><div className="flex items-center justify-between rounded-xl border border-border bg-muted/40 px-4 py-3"><div><p className="text-xs font-bold">Resume rewriting LLM</p><p className="mt-0.5 text-[11px] text-muted-foreground">Configured on the server through LLM_API_KEY</p></div><span className={`rounded-md px-2 py-1 text-[11px] font-bold ${settings.hasLLM ? "bg-[#e5f6ec] text-[#288258]" : "bg-[#fff4e4] text-[#9d6a28]"}`}>{settings.hasLLM ? "Ready" : "Not configured"}</span></div><p className="text-[11px] leading-5 text-muted-foreground">ATS scores and formatting checks work without an LLM. To get rewrite suggestions, set LLM_API_KEY in your server environment. The key never enters this page.</p>
        <div className="border-t border-border pt-4"><div className="flex items-center justify-between"><p className="text-xs font-bold">External humanizer <span className="font-normal text-muted-foreground">(optional)</span></p>{settings.hasHumanizerKey && <button onClick={() => clearKey("humanizerKey")} className="text-[11px] font-semibold text-rose-600 hover:underline">Remove saved key</button>}</div><p className="mt-1 text-[11px] leading-5 text-muted-foreground">Falls back to the built-in humanizer if unavailable. Receives resume text only when configured.</p><div className="mt-3 grid gap-2 sm:grid-cols-2"><Input aria-label="Humanizer HTTPS endpoint" type="url" placeholder="https://api.provider.com/humanize" value={humanizerUrl} onChange={e => setHumanizerUrl(e.target.value)} /><Input aria-label="Humanizer API key" type="password" autoComplete="off" placeholder={settings.hasHumanizerKey ? "Key saved · enter to replace" : "Your API key"} value={humanizerKey} onChange={e => setHumanizerKey(e.target.value)} /></div></div>
        <div className="border-t border-border pt-4"><div className="flex items-center justify-between"><p className="text-xs font-bold">AI-likelihood detector <span className="font-normal text-muted-foreground">(optional)</span></p>{settings.hasDetectorKey && <button onClick={() => clearKey("detectorKey")} className="text-[11px] font-semibold text-rose-600 hover:underline">Remove saved key</button>}</div><p className="mt-1 text-[11px] leading-5 text-muted-foreground">External detector scores each section. Without one, a transparent heuristic is used—not a claim of detection accuracy.</p><div className="mt-3 grid gap-2 sm:grid-cols-2"><Input aria-label="Detector HTTPS endpoint" type="url" placeholder="https://api.provider.com/score" value={detectorUrl} onChange={e => setDetectorUrl(e.target.value)} /><Input aria-label="Detector API key" type="password" autoComplete="off" placeholder={settings.hasDetectorKey ? "Key saved · enter to replace" : "Your API key"} value={detectorKey} onChange={e => setDetectorKey(e.target.value)} /></div></div>
      </CardContent></Card></div>
      <div className="space-y-4"><div className="rounded-2xl border border-[#d9d4f3] bg-[#f4f2ff] p-5 dark:border-[#50447c] dark:bg-[#2c2650]"><LockKeyhole size={20} className="text-primary" /><p className="mt-3 font-display text-sm font-bold">Private by design</p><p className="mt-2 text-xs leading-6 text-muted-foreground">Your saved jobs, applications, resume versions, and provider keys belong to your account. Provider keys are encrypted before storage.</p></div>
        <Card><CardHeader><CardTitle>Where jobs come from</CardTitle></CardHeader><CardContent className="space-y-3 text-xs text-muted-foreground"><p className="flex items-center gap-2"><Check size={14} className="text-[#279067]" /> Official Greenhouse, Lever, Ashby & Workable boards</p><p className="flex items-center gap-2"><Check size={14} className="text-[#279067]" /> YC company directory & their own ATS</p><p className="flex items-center gap-2"><Check size={14} className="text-[#279067]" /> Monthly HN Who is Hiring? thread</p><a href="https://www.dol.gov/agencies/eta/foreign-labor/performance" target="_blank" rel="noopener noreferrer" className="flex items-center gap-1 border-t border-border pt-3 font-semibold text-primary hover:underline">DOL filing data <ExternalLink size={13} /></a><a href="https://www.uscis.gov/tools/reports-and-studies/h-1b-employer-data-hub" target="_blank" rel="noopener noreferrer" className="flex items-center gap-1 font-semibold text-primary hover:underline">USCIS Employer Data Hub <ExternalLink size={13} /></a></CardContent></Card>
        <div className="rounded-xl border border-border bg-card p-4 text-[11px] leading-5 text-muted-foreground"><CircleHelp size={16} className="mb-2 text-primary" /><p>For setup, cron scheduling, government data import and custom provider contracts, see the <a href="https://github.com/PakshalShah30/the-bureau#readme" target="_blank" rel="noopener noreferrer" className="font-semibold text-primary hover:underline">project README</a>.</p></div>
      </div>
    </div>}
  </div>;
}
