"use client";
import { useEffect, useState } from "react";
import { formatDistanceToNow } from "date-fns";
import { toast } from "sonner";
import { Building2, CircleHelp, ExternalLink, FlaskConical, Plus, Search, Sparkles, Trash2 } from "lucide-react";
import type { AtsType, Company } from "@/lib/types";
import { request } from "@/lib/client";
import { Button } from "@/components/ui/button";
import { Input, Select } from "@/components/ui/input";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { PageHeading } from "@/components/layout/page-heading";
import { EmptyState } from "@/components/layout/empty-state";
import { Skeleton } from "@/components/ui/skeleton";
import { CompanyAvatar } from "@/components/jobs/job-card";
import { Badge } from "@/components/ui/badge";
const blank = { name: "", atsType: "GREENHOUSE" as AtsType, boardSlug: "", careersUrl: "", employerOverride: "" };
export default function CompaniesPage() {
  const [companies, setCompanies] = useState<Company[] | null>(null), [query, setQuery] = useState(""), [dialog, setDialog] = useState(false), [editing, setEditing] = useState<Company | null>(null);
  const [form, setForm] = useState(blank), [busy, setBusy] = useState(false), [test, setTest] = useState<string | null>(null), [importOpen, setImportOpen] = useState(false);
  const [batch, setBatch] = useState("W25"), [industry, setIndustry] = useState(""), [maxSize, setMaxSize] = useState("");
  const [importPage, setImportPage] = useState(0), [importSummary, setImportSummary] = useState("");
  useEffect(() => { request<{ companies: Company[] }>("/api/companies").then(d => setCompanies(d.companies)).catch(e => toast.error(e.message)); }, []);
  function open(co?: Company) { setEditing(co || null); setForm(co ? { name: co.name, atsType: co.atsType, boardSlug: co.boardSlug, careersUrl: co.careersUrl || "", employerOverride: co.employerOverride || "" } : blank); setTest(null); setDialog(true); }
  async function check() { setTest("Checking official board…"); try { const t = await request<{ count: number; sample: string | null }>("/api/companies/test", { method: "POST", body: JSON.stringify({ atsType: form.atsType, boardSlug: form.boardSlug }) }); setTest(`✓ Board found · ${t.count} open postings${t.sample ? ` · e.g. ${t.sample}` : ""}`); } catch (e) { setTest(`Could not reach board: ${e instanceof Error ? e.message : "Unavailable"}`); } }
  async function save(e: React.FormEvent) { e.preventDefault(); setBusy(true);
    try { const body = { name: form.name, atsType: form.atsType, boardSlug: form.boardSlug, careersUrl: form.careersUrl || null, employerOverride: form.employerOverride || null };
      const result = await request<{ company: Company }>(editing ? `/api/companies/${editing.id}` : "/api/companies", { method: editing ? "PATCH" : "POST", body: JSON.stringify(body) });
      setCompanies(prev => editing ? prev?.map(c => c.id === editing.id ? result.company : c) || null : [...(prev || []), result.company]); setDialog(false);
      toast.success(editing ? "Company updated" : "Company tracked — refresh to fetch its jobs");
    } catch (e) { toast.error(e instanceof Error ? e.message : "Could not save company"); } finally { setBusy(false); }
  }
  async function remove(co: Company) {
    if (!window.confirm(`Stop tracking ${co.name}? Its saved roles remain in your archive.`)) return;
    const before = companies; setCompanies(prev => prev?.filter(c => c.id !== co.id) || null); setDialog(false);
    try { await request(`/api/companies/${co.id}`, { method: "DELETE" }); toast.success(`${co.name} removed from tracking`); }
    catch (e) { setCompanies(before); toast.error(e instanceof Error ? e.message : "Could not remove company"); }
  }
  async function importYc(e: React.FormEvent) {
    e.preventDefault(); setBusy(true);
    try { const result = await request<{ discovered: number; tracked: number; noAts: number; already: number; nextPage: number | null; total: number; errors: string[] }>("/api/companies/import-yc", { method: "POST", body: JSON.stringify({ batch: batch || undefined, industry: industry || undefined, maxSize: maxSize ? Number(maxSize) : undefined, page: importPage }) });
      const { companies: fresh } = await request<{ companies: Company[] }>("/api/companies"); setCompanies(fresh); setImportPage(result.nextPage ?? 0);
      setImportSummary(`Page ${importPage + 1}: ${result.tracked} boards tracked; ${result.noAts} without a verified public board; ${result.already} previously tracked.${result.nextPage === null ? " No more results for these filters (or 1,000-result limit reached)." : " More results available."}`);
      toast.success(`${result.tracked} boards added from ${result.discovered} hiring YC companies. ${result.noAts} had no verified public ATS.`);
      if (result.errors.length) toast.warning(`${result.errors.length} boards could not be validated.`);
    } catch (e) { toast.error(e instanceof Error ? e.message : "YC import failed"); } finally { setBusy(false); }
  }
  const shown = companies?.filter(c => c.name.toLowerCase().includes(query.toLowerCase()) || c.boardSlug.toLowerCase().includes(query.toLowerCase())) || [];
  return <div><PageHeading eyebrow="YOUR SOURCES" title="Tracked companies" description="Follow official career boards, not reposts. Every role links back to where the company published it." action={<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setImportOpen(true)}><Sparkles size={15} /> Import YC startups</Button><Button onClick={() => open()}><Plus size={15} /> Track company</Button></div>} />
    <div className="mb-5 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><p className="text-[13px] text-muted-foreground">{companies ? `${companies.length} career boards tracked` : "Loading boards…"} <span className="mx-2">·</span> Greenhouse, Lever, Ashby & Workable</p><div className="relative sm:w-60"><Search size={15} className="absolute left-3 top-3 text-muted-foreground" /><Input placeholder="Find a company" aria-label="Find a company" value={query} onChange={e => setQuery(e.target.value)} className="pl-9" /></div></div>
    {!companies ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 6 }, (_, i) => <Skeleton key={i} className="h-40" />)}</div> : !shown.length ? <EmptyState icon={<Building2 size={24} />} title={query ? "No matching companies" : "Track your first company"} description={query ? "Try another name or board slug." : "Add a company's official ATS board to start getting fresh roles from the source."} action={<Button onClick={() => { setQuery(""); open(); }}><Plus size={15} /> Track company</Button>} /> : <div className="grid gap-3.5 md:grid-cols-2 xl:grid-cols-3">{shown.map(co => <article key={co.id} className="card-hover surface flex flex-col p-5"><div className="flex items-start justify-between"><CompanyAvatar name={co.name} size="md" /><div className="flex gap-1"><button onClick={() => open(co)} title={`Edit ${co.name}`} className="rounded-lg px-2 py-1 text-xs font-semibold text-muted-foreground hover:bg-muted hover:text-primary">Edit</button><button onClick={() => remove(co)} title={`Remove ${co.name}`} aria-label={`Stop tracking ${co.name}`} className="rounded-lg p-1.5 text-muted-foreground hover:bg-rose-50 hover:text-rose-600 dark:hover:bg-rose-950"><Trash2 size={15} /></button></div></div>
      <h2 className="mt-4 font-display text-[16px] font-bold">{co.name}</h2><div className="mt-2 flex flex-wrap gap-1.5"><Badge className="border-border bg-muted/70 text-muted-foreground">{co.atsType.charAt(0) + co.atsType.slice(1).toLowerCase()}</Badge>{co.ycBatch && <Badge className="source-yc">✦ YC {co.ycBatch}</Badge>}{co.industry && <Badge className="border-border bg-card text-muted-foreground">{co.industry}</Badge>}</div>
      <div className="mt-auto flex items-center justify-between border-t border-border pt-4 text-[11px] text-muted-foreground" style={{ marginTop: 20 }}><span className="flex items-center gap-1.5"><span className={`h-1.5 w-1.5 rounded-full ${co.lastError ? "bg-amber-500" : "bg-[#52b889]"}`} />{co.lastError ? "Source unavailable" : co.lastFetchedAt ? `Checked ${formatDistanceToNow(new Date(co.lastFetchedAt), { addSuffix: true })}` : "Waiting for first refresh"}</span>{co.careersUrl && <a href={co.careersUrl} target="_blank" rel="noopener noreferrer" aria-label={`${co.name} career board`} className="text-primary hover:underline"><ExternalLink size={15} /></a>}</div>
      {co.lastError && <p className="mt-2 truncate text-[10px] text-amber-700 dark:text-amber-300" title={co.lastError}>{co.lastError}</p>}
    </article>)}</div>}
    <div className="mt-6 flex gap-3 rounded-xl border border-border bg-card px-4 py-3 text-xs leading-5 text-muted-foreground"><CircleHelp size={17} className="shrink-0 text-primary" /><p>New boards are validated with a test fetch before saving. A failed source never marks its existing jobs closed. Refresh the job feed after adding a board.</p></div>
    <Dialog open={dialog} onOpenChange={setDialog}><DialogContent><DialogTitle>{editing ? `Edit ${editing.name}` : "Track a company"}</DialogTitle><DialogDescription>Enter the company&apos;s official public ATS board. We&apos;ll test it before saving.</DialogDescription><form onSubmit={save} className="mt-5 space-y-4"><div><label htmlFor="co-name" className="mb-1.5 block text-xs font-bold">Company name</label><Input id="co-name" value={form.name} onChange={e => setForm(v => ({ ...v, name: e.target.value }))} required placeholder="e.g. Figma" /></div><div className="grid grid-cols-2 gap-3"><div><label htmlFor="co-ats" className="mb-1.5 block text-xs font-bold">ATS platform</label><Select id="co-ats" value={form.atsType} onChange={e => { setTest(null); setForm(v => ({ ...v, atsType: e.target.value as AtsType })); }}><option value="GREENHOUSE">Greenhouse</option><option value="LEVER">Lever</option><option value="ASHBY">Ashby</option><option value="WORKABLE">Workable</option></Select></div><div><label htmlFor="co-slug" className="mb-1.5 block text-xs font-bold">Board slug</label><Input id="co-slug" value={form.boardSlug} onChange={e => { setTest(null); setForm(v => ({ ...v, boardSlug: e.target.value })); }} required placeholder="e.g. figma" /></div></div><p className="rounded-lg bg-muted px-3 py-2 text-[11px] leading-5 text-muted-foreground">Find the slug in the official board URL: jobs.ashbyhq.com/<strong>company</strong>, jobs.lever.co/<strong>company</strong>, or job-boards.greenhouse.io/<strong>company</strong>.</p><div><label htmlFor="co-careers" className="mb-1.5 block text-xs font-bold">Careers URL <span className="font-normal text-muted-foreground">(optional)</span></label><Input id="co-careers" type="url" value={form.careersUrl} onChange={e => setForm(v => ({ ...v, careersUrl: e.target.value }))} placeholder="https://company.com/careers" /></div><div><label htmlFor="co-override" className="mb-1.5 block text-xs font-bold">H-1B employer name override <span className="font-normal text-muted-foreground">(optional)</span></label><Input id="co-override" value={form.employerOverride} onChange={e => setForm(v => ({ ...v, employerOverride: e.target.value }))} placeholder="Exact DOL / USCIS employer name" /><p className="mt-1 text-[11px] text-muted-foreground">Use when the legal filer name differs from the brand.</p></div>{test && <p role="status" className={`rounded-lg px-3 py-2 text-xs ${test.startsWith("✓") ? "bg-[#eaf8f0] text-[#1b7952]" : "bg-[#fff5e8] text-[#a06b25]"}`}>{test}</p>}
      <div className="flex justify-between gap-2 border-t border-border pt-4"><Button type="button" variant="outline" size="sm" onClick={check} disabled={!form.boardSlug || busy}><FlaskConical size={15} /> Test fetch</Button><div className="flex gap-2"><Button type="button" variant="ghost" onClick={() => setDialog(false)}>Cancel</Button><Button disabled={busy}>{busy ? "Validating…" : editing ? "Save changes" : "Track company"}</Button></div></div>
    </form></DialogContent></Dialog>
    <Dialog open={importOpen} onOpenChange={setImportOpen}><DialogContent><DialogTitle>Find hiring YC startups</DialogTitle><DialogDescription>Search YC’s directory in pages of 32. Track hiring companies only when a first-party ATS board can be verified.</DialogDescription><form onSubmit={importYc} className="mt-5 space-y-4"><div className="grid grid-cols-2 gap-3"><div><label htmlFor="yc-batch" className="mb-1.5 block text-xs font-bold">YC batch</label><Input id="yc-batch" value={batch} onChange={e => { setBatch(e.target.value); setImportPage(0); setImportSummary(""); }} placeholder="W25" /></div><div><label htmlFor="yc-industry" className="mb-1.5 block text-xs font-bold">Industry</label><Input id="yc-industry" value={industry} onChange={e => { setIndustry(e.target.value); setImportPage(0); setImportSummary(""); }} placeholder="B2B" /></div></div><div><label htmlFor="yc-size" className="mb-1.5 block text-xs font-bold">Max team size <span className="font-normal text-muted-foreground">(optional)</span></label><Input id="yc-size" type="number" min={1} max={10000} value={maxSize} onChange={e => { setMaxSize(e.target.value); setImportPage(0); setImportSummary(""); }} placeholder="e.g. 50" /></div><p className="rounded-xl bg-accent p-3 text-[11px] leading-5 text-accent-foreground">Only YC&apos;s public directory and the company&apos;s own career board are used. Companies without a verified board are skipped, never guessed. Use the next-page button to continue. Narrow filters if the 1,000-result directory limit is reached. Large imports may take a few minutes.</p>{importSummary && <p role="status" className="rounded-lg bg-muted p-3 text-xs leading-5">{importSummary}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setImportOpen(false)}>Cancel</Button><Button disabled={busy || (!batch && !industry)}><Sparkles size={15} />{busy ? "Discovering boards…" : importPage ? `Track next page (${importPage + 1})` : "Track first page"}</Button></div></form></DialogContent></Dialog>
  </div>;
}
