"use client";
import { use, useEffect, useState } from "react";
import Link from "next/link";
import { formatDistanceToNow } from "date-fns";
import { toast } from "sonner";
import { ArrowLeft, ArrowUpRight, Bookmark, BriefcaseBusiness, CalendarDays, CircleHelp, ExternalLink, MapPin, ShieldCheck, Sparkles } from "lucide-react";
import type { Job, SavedJob, VisaFiling } from "@/lib/types";
import { request } from "@/lib/client";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { CompanyAvatar } from "@/components/jobs/job-card";
import { SourceBadge, SponsorBadge } from "@/components/jobs/job-badges";
type Detail = { job: Job; saved: SavedJob | null; filings: VisaFiling[]; filingSummary: { records: number; lcaFilings: number; uscisApprovals: number; uscisDenials: number; medianWage: number | null; commonTitles: Array<{ title: string; count: number }>; years: number[] }; matchedEmployer: string };
export default function JobDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const [data, setData] = useState<Detail | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState("");
  useEffect(() => { setError(""); setData(null); request<Detail>(`/api/jobs/${id}`).then(setData).catch(e => setError(e instanceof Error ? e.message : "Could not load job")); }, [id]);
  async function toggle() {
    if (!data || busy) return;
    const before = data.saved; setData({ ...data, saved: before ? null : { id: "optimistic", userId: data.job.userId, jobId: id, notes: "", tags: [], createdAt: new Date().toISOString() } }); setBusy(true);
    try { await request(`/api/saved${before ? `/${id}` : ""}`, { method: before ? "DELETE" : "POST", ...(before ? {} : { body: JSON.stringify({ jobId: id }) }) }); toast.success(before ? "Removed from saved jobs" : "Saved to your shortlist"); }
    catch (e) { setData(d => d ? { ...d, saved: before } : d); toast.error(e instanceof Error ? e.message : "Could not update job"); } finally { setBusy(false); }
  }
  if (error) return <div className="surface p-10 text-center"><p className="font-display font-bold">Could not load this job</p><p className="mt-2 text-sm text-muted-foreground">{error}</p><Button asChild className="mt-5"><Link href="/jobs">Back to job feed</Link></Button></div>;
  if (!data) return <div className="space-y-6"><Skeleton className="h-5 w-40" /><Skeleton className="h-52 w-full" /><div className="grid gap-5 lg:grid-cols-[1fr_320px]"><Skeleton className="h-96" /><Skeleton className="h-64" /></div></div>;
  const { job, filingSummary: history } = data;
  return <div><Link href="/jobs" className="mb-6 inline-flex items-center gap-2 text-xs font-bold text-muted-foreground hover:text-primary"><ArrowLeft size={15} /> Back to job feed</Link>
    <div className="surface mb-6 p-6 sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div className="flex items-start gap-4"><CompanyAvatar name={job.companyName} size="lg" /><div><p className="mb-1 text-sm font-semibold text-muted-foreground">{job.companyName} {job.ycBatch && <span className="ml-1 text-xs text-amber-600">✦ YC {job.ycBatch}</span>}</p><h1 className="max-w-2xl font-display text-[24px] font-extrabold leading-tight tracking-[-.05em] sm:text-[29px]">{job.title}</h1><div className="mt-3 flex flex-wrap gap-2"><SourceBadge source={job.source} batch={job.ycBatch} /><SponsorBadge status={job.sponsorship} />{!!job.closedAt && <span className="rounded-full border border-border px-2 py-0.5 text-[11px] font-semibold text-muted-foreground">Closed</span>}</div></div></div>
      <div className="flex shrink-0 gap-2"><Button variant="outline" onClick={toggle} disabled={busy} aria-label={data.saved ? "Remove saved job" : "Save job"}><Bookmark size={16} fill={data.saved ? "currentColor" : "none"} />{data.saved ? "Saved" : "Save job"}</Button><Button asChild><a href={job.originalUrl} target="_blank" rel="noopener noreferrer">Apply on company site <ExternalLink size={15} /></a></Button></div></div>
      <div className="mt-6 flex flex-wrap gap-x-6 gap-y-2 border-t border-border pt-5 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1.5"><MapPin size={15} />{job.location || "Not specified"} {job.workplace !== "UNSPECIFIED" && <span>· {job.workplace.toLowerCase()}</span>}</span><span className="inline-flex items-center gap-1.5"><CalendarDays size={15} />{job.postedAt ? `Posted ${formatDistanceToNow(new Date(job.postedAt), { addSuffix: true })}` : "Date not provided by source"}</span>{job.department && <span className="inline-flex items-center gap-1.5"><BriefcaseBusiness size={15} />{job.department}</span>}{job.companySize && <span>Reported size: {job.companySize.toLocaleString()} people</span>}</div>
    </div>
    <div className="grid items-start gap-5 lg:grid-cols-[minmax(0,1fr)_minmax(290px,330px)]"><div className="space-y-5"><Card><CardHeader><CardTitle>About this role</CardTitle><p className="mt-1 text-xs text-muted-foreground">From the original {job.atsType ? `${job.atsType.toLowerCase()} posting` : "HN comment"} · no third-party reposts</p></CardHeader><CardContent>{job.description ? <div className="whitespace-pre-line text-[13px] leading-[1.9] text-foreground/85">{job.description}</div> : <div className="rounded-xl bg-muted p-5 text-sm text-muted-foreground">The public board did not provide a description in its API. Read the full role on the company site. No description has been fabricated.</div>}{process.env.NEXT_PUBLIC_DEMO_MODE === "true" && <p className="mt-4 text-xs text-muted-foreground">Dated preview: descriptions are source excerpts, not full postings. Refresh against the official company board before evaluating fit or trusting an ATS score.</p>}</CardContent></Card>
      <Card><CardHeader><CardTitle>Original source</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><a target="_blank" rel="noopener noreferrer" href={job.originalUrl} className="flex items-center justify-between gap-2 rounded-xl border border-border p-3.5 font-medium text-primary hover:bg-accent"><span className="truncate">Company&apos;s original posting</span><ArrowUpRight size={16} /></a>{job.hnUrl && <a target="_blank" rel="noopener noreferrer" href={job.hnUrl} className="flex items-center justify-between gap-2 rounded-xl border border-border p-3.5 font-medium text-primary hover:bg-accent"><span>Read the original HN comment</span><ArrowUpRight size={16} /></a>}{job.source === "YC_STARTUP" && job.sourceUrl && <a target="_blank" rel="noopener noreferrer" href={job.sourceUrl} className="flex items-center justify-between gap-2 rounded-xl border border-border p-3.5 font-medium text-primary hover:bg-accent"><span>YC company profile</span><ArrowUpRight size={16} /></a>}</CardContent></Card></div>
      <div className="space-y-5 lg:sticky lg:top-24"><Card><CardHeader><div className="mb-2 flex h-10 w-10 items-center justify-center rounded-xl bg-[#eaf8f1] text-[#279067] dark:bg-[#214335]"><ShieldCheck size={19} /></div><CardTitle>H-1B sponsorship</CardTitle><p className="mt-1 text-xs text-muted-foreground">Evidence, not a promise</p></CardHeader><CardContent><SponsorBadge status={job.sponsorship} />
        {job.sponsorshipEvidence ? <div className="mt-4 rounded-xl border-l-[3px] border-primary bg-muted/70 px-3.5 py-3"><p className="text-[11px] font-bold uppercase tracking-wider text-muted-foreground">EXACT WORDS IN POSTING</p><blockquote className="mt-2 text-[13px] leading-6">“{job.sponsorshipEvidence}”</blockquote></div> : <p className="mt-4 text-[13px] leading-6 text-muted-foreground">{job.sponsorship === "LIKELY_HISTORY" ? "No explicit job policy. Recent employer filings are shown below." : "No explicit sponsorship policy found in this posting. Do not assume either way."}</p>}
        <p className="mt-4 flex items-start gap-2 border-t border-border pt-4 text-[11px] leading-5 text-muted-foreground"><CircleHelp size={14} className="mt-0.5 shrink-0" /> Sponsorship status is inferred — confirm with the recruiter.</p>
      </CardContent></Card>
      <Card><CardHeader><CardTitle>Employer filing history</CardTitle><p className="mt-1 text-xs text-muted-foreground">Official DOL & USCIS data · last 3 years</p></CardHeader><CardContent>{history.records ? <><div className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-muted p-3"><p className="font-display text-xl font-bold">{history.lcaFilings}</p><p className="text-[11px] text-muted-foreground">LCA records</p></div><div className="rounded-xl bg-muted p-3"><p className="font-display text-xl font-bold">{history.uscisApprovals}</p><p className="text-[11px] text-muted-foreground">USCIS approvals</p></div></div>{history.medianWage && <p className="mt-4 text-xs"><strong>Median offered wage:</strong> ${Math.round(history.medianWage).toLocaleString()} / year</p>}{history.commonTitles.length > 0 && <div className="mt-4"><p className="mb-2 text-[11px] font-bold uppercase tracking-wide text-muted-foreground">COMMON LCA JOB TITLES</p>{history.commonTitles.map(t => <p key={t.title} className="py-1 text-xs">{t.title} <span className="text-muted-foreground">({t.count})</span></p>)}</div>}<p className="mt-4 text-[11px] text-muted-foreground">Fiscal years {history.years.join(", ")} · employer match: {data.matchedEmployer}</p>
        <details className="mt-4 border-t border-border pt-3"><summary className="cursor-pointer text-xs font-semibold text-primary">View filing details ({Math.min(history.records, data.filings.length)} shown)</summary><div className="mt-3 max-h-80 space-y-2 overflow-y-auto pr-1">{data.filings.map(f => <div key={f.id} className="rounded-lg border border-border bg-muted/40 p-3 text-[11px]"><a href={f.sourceUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 font-bold text-primary hover:underline">{f.source === "DOL_LCA" ? "DOL certified LCA" : "USCIS adjudications"} · FY{f.fiscalYear} <ArrowUpRight size={12} /></a><p className="mt-1 font-medium">{f.employerName}{f.title ? ` · ${f.title}` : " · employer-level data"}</p>{f.worksite && <p className="mt-1 text-muted-foreground">{f.worksite}</p>}{f.wage && <p className="mt-1 text-muted-foreground">Offered annual wage: ${Math.round(f.wage).toLocaleString()}</p>}{f.approvals !== null && <p className="mt-1 text-muted-foreground">Approvals: {f.approvals} · denials: {f.denials ?? "not reported"}</p>}</div>)}</div></details>
        <p className="mt-3 text-[11px] leading-5 text-muted-foreground">An LCA is not an H-1B approval; USCIS totals are adjudications, not hires. Historical activity does not guarantee sponsorship for this position. Always confirm with the employer.</p></> : <div className="rounded-xl bg-muted/80 p-4"><p className="text-xs font-semibold">No matching filings imported</p><p className="mt-1 text-[11px] leading-5 text-muted-foreground">Unknown is not the same as no sponsorship. Import government data to enable history signals.</p></div>}</CardContent></Card>
      <div className="rounded-2xl border border-[#ded8f8] bg-[#f4f1ff] p-5 dark:border-[#4d417a] dark:bg-[#302950]"><Sparkles size={20} className="text-primary" /><p className="mt-3 font-display text-sm font-bold">Make your experience fit.</p><p className="mt-1.5 text-xs leading-5 text-muted-foreground">See your ATS match and tailor your real experience for this role.</p><Button asChild size="sm" className="mt-4 w-full"><Link href={`/resumes?jobId=${job.id}`}>Tailor a resume <ArrowUpRight size={14} /></Link></Button></div>
      </div>
    </div>
  </div>;
}
